#!/usr/bin/env bash
# bash script that give out information about subdomains
domin(){
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}
if [ "$#" == 1 ]
then
  domin "$1" "www"
  domin "$1" "lb-01"
  domin "$1" "web-01"
  domin "$1" "web-02"
elif [ "$#" == 2 ]
then
  domin "$1" "$2"
fi
