#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me

apt-get update
apt-get install -y nginx
echo "Hello world!" > /etc/nginx/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.linkedin.com/in/mubtunj;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
