#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www/html
echo "Hello World!" |sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html
sudo sed -i "/listen 80 default_server/a \\\trewrite ^/redirect_me https://www.linkedin.com/in/mubtunj permanent;" /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server/a \\\terror_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n\tinternal;}" /etc/nginx/sites-available/default
sudo sed -i "/listen 80 default_server/a \\\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default

sudo service nginx restart
