#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

sudo apt-get update
sudo apt-get install -y HAproxy

server_config=\
"
frontend mubtunj-frontend
    bind *:80
    mode http
    default_backend mubtunj_backend

backend mubtunj_backend
    balance roundrobin
    server 181306-web-01 54.146.66.65 check
    server 181306-web-02 34.207.212.18 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
